Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Metrics/LineLength:
  Exclude:
    - 'bin/spring'
    - 'db/*'
    - 'db/migrate/*'
    - 'config/initializers'
